// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxwxhmnsyjshsnycldea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4d3hobW5zeWpzaHNueWNsZGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NTc0NTEsImV4cCI6MjA3MTIzMzQ1MX0.1p-H4uhGlmdJh9dy0BeePOaIPjtodZvXSFHQJbWS2xI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});